name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install Node.js and dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install project dependencies
        run: npm install
      - name: Build the project and deploy to GitHub Pages
        run: |
          npm run build
          echo "/*    /your-repo-name/" > dist/_redirects # adjust the path accordingly
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.token }}
          publish_dir: ./dist
